name: PeaceControl
main: peaceman.peacecontrol.PeaceControl
version: 0.1
commands:
    info:
        description: PeaceControl Help
        aliases: [pc,peacecontrol]
        usage: /<command>
    user:
        description: User Management
        aliases: [u, user]
        usage: /<command> <action> [<parameters>]
    user.register:
        description: Registers a user
        aliases: [register, reg]
        usage: /<command> <password> [<email>]
    user.login:
        description: Login a user
        aliases: [login, l]
        usage: /<command> <password>
    user.logout:
        description: Kills a user session
        aliases: [logout]
        usage: /<command>
    user.changePassword:
        description: Changes the user password
        aliases: [changepw, changepassword]
        usage: /<command> <oldpassword> <newpassword>
    user.delete:
        description: Deletes the user account
        aliases: [deleteaccount, deregister]
        usage: /<command> <password>
        